services:
  autotrain-advanced:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autotrain-advanced
    restart: no
    command: nvidia-smi
    entrypoint: ['bash', '-c', 'pip install autotrain-advanced && autotrain setup && autotrain llm --train --project_name "llama2_experimenth2go" --model TinyPixel/Llama-2-7B-bf16-sharded --data_path remco-lutrasoft/lutra_experiment --text-column text --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 2 --num_train_epochs 3 --trainer sft --model_max_length 2048 --push_to_hub --token "my_token_here" --repo_id "remco-lutrasoft/lutra_experiment" --block_size 2048 > training.log']
    ports:
      - 8007:8007
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
